version: "3.8"

services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SimplePass!2024
      POSTGRES_DB: geo_database
    ports:
      - 5438:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "geo_database", "-h", "localhost", "-p", "5432"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:SimplePass!2024@db:5432/geo_database
      - GEOJSON_URL=https://file.notion.so/f/f/9301458a-f465-42d3-80eb-7c09bae15034/282d7ed4-5168-4e77-91be-59906c19f9f3/Map_(10).geojson?table=block&id=655f6883-c12c-4503-bd82-157ea8ee1571&spaceId=9301458a-f465-42d3-80eb-7c09bae15034&expirationTimestamp=1733508000000&signature=pxNn_GtkzVZ3wnwKnwbCrWJnIfBqEgnvVEEnb3WqdQs&downloadName=karnataka.geojson
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
